### ISSUE TITLE
Audio Device Selector ignores exec_path

### ISSUE THREAD

**Issue by ankushg** [rknightuk/alfred-workflows#11]
ADS doesn't seem to be working for me

It instructs you to configure an `exec_path` and I think I've done so correctly.

From looking at the source though, it looks like it's just using a hardcoded path (that isn't correct for me) instead of checking `exec_path`: https://github.com/rknightuk/alfred-workflows/blob/main/workflows/audio-device-selector/src/script.js#L7

**Comment by cmer** [comment]
Same issue here. Doesn't work on Apple Silicon because of this bug, unfortunately.

**Comment by rknightuk** [comment]
This is now fixed if you redownload.
