### ISSUE TITLE
Agenda html output doesn't handle umlauts

### ISSUE THREAD

**Issue by OddMagnet** [rknightuk/alfred-workflows#12]
When viewing events or reminders in alfred, they're displayed just fine, but when viewing the html overview they're not displayed correctly

eg. 'nächstes' becomes 'naÌˆchstes'

At first I thought the html file might just have the wrong encoding, but it has utf-8 which should be correct

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
