### ISSUE TITLE
Support Tags!

### ISSUE THREAD

**Issue by cromulus** [rknightuk/alfred-workflows#13]
Hi!
The new tag functionality in Reminders.app is amazing. Would love to see support for that in this workflow!

Right now, with both the fantastical and plain old reminders integration, the tags aren't added to the reminder.

Thanks!

**Comment by timlawson-uk** [comment]
Agree! Would like to see support for the Tags in Reminders as I use them with almost every reminder I make. Is this something you are able to do @rknightuk ?

**Comment by rknightuk** [comment]
It doesn't look like the API supports tags unfortunately https://developer.apple.com/documentation/eventkit/ekreminder

**Comment by cromulus** [comment]
Pants. I'll pester apple then!

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
