### ISSUE TITLE
Too many calendars

### ISSUE THREAD

**Issue by TookiTheGreat** [rknightuk/alfred-workflows#15]
Hi Robb,

I love this workflow and am deffo planning to buy you that coffee. But before I do (minor bribe coming up): would it be possible to tell Alfred to pick events from specific calendars rather than all of the calendars available? I have 12 email accounts (one for each of my current clients) and all of them have their own calendar. Running your Agenda script often returns duplicates for events that I copied across to other calendars to make sure those times are blocked everywhere. It would be great if I could pass the preferred calendar(s) as an argument to the script but I'm not smart enough to figure that our for myself.

Oh, and while we're at it: is there an easy way to strip away the XML/HTML code, so I'm left with the bare texts only? That would be handy to send to the clipboard so I can paste it into Obsidian, for instance.

**Comment by TookiTheGreat** [comment]
Never mind my last comment (about stripping away the XML/HTML tags. I managed to locate the script you use to build the output string and have changed it to my personal preferences :-).

I think I may be able to do a post-selection of the items from a single calendar only, but that will require some more thinking and studying. I will get it in the end, I'm sure, but if you have some tips or suggestions, that would be most welcome.

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
