### ISSUE TITLE
Change theme doesn't do anything

### ISSUE THREAD

**Issue by a-rock-lobster** [rknightuk/alfred-workflows#16]
Thanks for sharing the workflow.

My alfred is a light colour and I'm trying the change the theme. The notification shows up but nothing else happens.

Cheers,

**Comment by rknightuk** [comment]
Which workflow is this related to? I don't have one to change themes that I was aware of.

**Comment by a-rock-lobster** [comment]
Oh I'm sorry, I didn't read carefully enough. It is to change the overview theme, not the alfred icons which I presumed. I hadn't figured out what the overview was at this point. Sorry again.

**Comment by rknightuk** [comment]
No problem 🙂️

**Comment by a-rock-lobster** [comment]
I put together a dark set of icons. They are the same icons you used and can simply be dragged into the icon folder to replace the light ones. It involves alot of downloading, converting to PNG and renaming. I don't know if there is anyway to include a folder in the workflow in which they can be stored for users to drag them over if they use a light coloured Alfred? I can send them to you if you think this is of any use.
