### ISSUE TITLE
Gives index.js error

### ISSUE THREAD

**Issue by bhishanpdl** [rknightuk/alfred-workflows#18]
This seems to be a great workflow, lots of work put on this workflow.
Unfortunately, it is giving me some errors:

Date: Jan 13, 2022

```
ERROR: Agenda - Reminders and Calendar Events[Script Filter] Code 1: ./scripts/upcoming/index.js: execution error: Error: SyntaxError: JSON Parse error: Expected '}' (-2700)
```

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
