### ISSUE TITLE
Feature Request: Set priority in new reminder

### ISSUE THREAD

**Issue by whazlewo** [rknightuk/alfred-workflows#23]
I love how you are parsing the dates. Do you think it would be possible to add a parse pass to look for exclamation points for priority?

E.g.

Lunch with Rob tomorrow at 11:30am !  (low priority)
First Draft of TPS Report tomorrow !!! (high priority)

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
