### ISSUE TITLE
“agendas” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by trueschool** [rknightuk/alfred-workflows#25]
Mac won't let me run Agendas workflows. Is there a fix for this? Thanks -- looks like a cool wkflow!

**Comment by csatwood** [comment]
> Mac won't let me run Agendas workflows. Is there a fix for this? Thanks -- looks like a cool wkflow!

I had to approved it the System Settings under Privacy and then I could get the "Open" option to show the next time I ran it. I think this the higher level gateway stuff Apple added blocking things that aren't notarized.

**Comment by csatwood** [comment]
Though now it won't work because of the issue outlined [here](https://github.com/rknightuk/alfred-workflows/issues/35#issue-1972542624).

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
