### ISSUE TITLE
Cannot configure Agenda

### ISSUE THREAD

**Issue by MaralWa** [rknightuk/alfred-workflows#27]
Hi,

I just installed the latest version of the Agenda workflow but I cannot configure it. I clicked on "Configure Workflow" but then I cannot add a new configuration and no existing configuration is shown:

![Bildschirmfoto 2022-12-04 um 17 35 51](https://user-images.githubusercontent.com/18118847/205503710-15f93e7d-1862-43f3-b7e7-3fd7771f5d00.png)

I am using Alfred 5.0.5

Ciao

Maral

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
