### ISSUE TITLE
Creating reminders with a time doesn't work

### ISSUE THREAD

**Issue by bobby-huang** [rknightuk/alfred-workflows#29]
Creating reminders works without a specific time. 

Creating them with a time like "lunch with john 11:00am" doesn't work.
![2023-01-02-06-55-50-cst-you-are-loved](https://user-images.githubusercontent.com/10715152/210234235-9340b444-28b8-4188-8fd7-32dd8f9ecf0f.jpg)

**Comment by pvs-praneeth** [comment]
seeing the same issue.

**Comment by davaba86** [comment]
Same here, simple reminder with just a string does not create it :(

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
