### ISSUE TITLE
Adding a task with no due date seems to fail

### ISSUE THREAD

**Issue by ismh** [rknightuk/alfred-workflows#3]

**Comment by rknightuk** [comment]
oh no

**Comment by ismh86** [comment]
They just go _nowhere_

**Comment by rknightuk** [comment]
I see the issue, working on it now.

**Comment by rknightuk** [comment]
Version 1.0.1 is up, fixes this issue https://github.com/rknightuk/alfred-workflows/raw/main/workflows/reminders/reminders.alfredworkflow

**Comment by ismh86** [comment]
AM I A DEVELOPER NOW

**Comment by rknightuk** [comment]
You did a good GitHub so yes
