### ISSUE TITLE
Not working - "You need to grand reminders access"

### ISSUE THREAD

**Issue by mogelbrod** [rknightuk/alfred-workflows#35]
I installed this workflow a while back and thought it worked great, nice work!
Unfortunately it has stopped working sometime during the past couple of months, likely after a Mac OS or Alfred update.

With MacOS Sonoma 14.1 installed I'm getting the following error in the debug log when choosing "Agenda" or "Today Overview" in the alfred prompt:

```
[15:53:33.956] Agenda - Reminders and Calendar Events[Script Filter] Script with argv '(null)' finished
[15:53:33.966] ERROR: Agenda - Reminders and Calendar Events[Script Filter] Code 1: ./scripts/upcoming/index.js: execution error: Error: Error: You need to grant reminders access (1)
```

Unfortunately it's not really clear how to grant this access. Alfred 5, iTerm and Terminal all have access to Reminders:
<img width="490" alt="Screenshot 2023-11-01 at 15 54 54" src="https://github.com/rknightuk/alfred-workflows/assets/150084/97911662-2458-4c0a-98dd-fe40b1ebc79f">

I tried manually running the `agendas` CLI executable from the workflow directory but it didn't ask for access to Reminders when launching.

- Alfred v5.1.4 [2195]
- Agenda v1.0.1

Thanks in advance!

**Comment by davetorbeck** [comment]
Also getting this

**Comment by taylorbrooks** [comment]
Also getting this.

**Comment by csatwood** [comment]
Also getting this.

**Comment by eytanschulman** [comment]
Same

**Comment by ceagnew** [comment]
Same

**Comment by mlevison** [comment]
FWIW This thread on the Alfred Forum covers much of this issue: https://www.alfredforum.com/topic/17163-agenda-reminders-and-calendar-events-workflow/page/2/#comments

**Comment by mogelbrod** [comment]
> FWIW This thread on the Alfred Forum covers much of this issue: [alfredforum.com/topic/17163-agenda-reminders-and-calendar-events-workflow/page/2/#comments](https://www.alfredforum.com/topic/17163-agenda-reminders-and-calendar-events-workflow/page/2/#comments)

Looks like that might've worked, thanks for sharing!

**Comment by rknightuk** [comment]
https://github.com/rknightuk/alfred-workflows/issues/39
