### ISSUE TITLE
All Pages option doesn't work

### ISSUE THREAD

**Issue by rkranendonk** [rknightuk/alfred-workflows#38]
If I select 'All Pages' the workflow still asks me to specify the pages I want to copy, after I have selected the Link Format

**Comment by rknightuk** [comment]
That's how it works, so you can say give me `1,3,5` of the tabs, if you just hit enter it will copy all of them.

**Comment by rkranendonk** [comment]
Thanks!
I would recommend putting something like ‘Hit Enter for all’ into the last dialog box.
But maybe it’s just me.

--

Met vriendelijke groet, Kind regards,
Richard Kranendonk
t: +31 6 286 388 46
